# bytes
HEADER_TYPE_BET_BATCH = 0x01
HEADER_TYPE_CONFIRM = 0x02
HEADER_TYPE_FAILURE = 0x03
HEADER_TYPE_FINISH_NOTIFY = 0x04
HEADER_TYPE_WINNERS_QUERY = 0x05
HEADER_TYPE_WINNERS_LIST = 0x06
HEADER_SIZE = 3
CONFIRMATION_LENGTH = 0